development: &development
  adapter: sqlite3
  database: "db/development.sqlite3"

test:
  <<: *development
  database: "db/test.sqlite3"

production:
  adapter: mysql
  username: username
  password: password
  host: host
  database: database
